global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 1s

scrape_configs:

  - job_name: 'otel-collector'
    static_configs:
    - targets: ['opentelemetry:8889']
    - targets: ['opentelemetry:8888']
