name: Esteira de Integração Contínua e Deploy Contínuo da Ntickets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runSonar:
        description: 'Rodar Análise Estática do Código'
        type: boolean
        required: false
        default: true
      runFunctionTests:
        description: 'Rodar Testes De Aceitação'
        type: boolean
        required: false
        default: true

jobs:
  build-application:
    name: Construção da Aplicação
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    - name: Instalação das Dependências do .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Testar Construção da Aplicação
      run: |
         dotnet build
  acceptance-tests:
    name: Testes de Aceitação
    runs-on: ubuntu-latest
    environment: Production
    needs: build-application
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    - name: Instalação das Dependências do .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Instalação das Dependências do .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restaurar Dependências da Solução
      run: dotnet restore Ntickets.sln
    - name: Implantar Dependências do Docker
      run: docker compose -f "./devops/local/docker-compose.Local.yaml" up -d
    - name: Instalar Ferramenta de Migração do Banco de Dados
      run: |
        dotnet tool install --global dotnet-ef
    - name: Aplicar Migração do Banco de Dados
      run: |
        dotnet ef database update --project "./src/Ntickets.WebApi/Ntickets.WebApi.csproj"
    - name: Executar Aplicação .NET 8
      run: |
        dotnet dev-certs https --trust
        dotnet dev-certs https --check
        dotnet run --project "./src/Ntickets.WebApi/Ntickets.WebApi.csproj" & echo $! > pidfile
    - name: Rodar Testes de Aceitação na Aplicação
      run: |
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal ./tsts/functional/Ntickets.FunctionalTests/Ntickets.FunctionalTests.csproj
    - name: Parar Aplicação
      run: |
        kill $(cat pidfile)
        rm pidfile
    - name: Parar as Dependências do Docker
      if: always() 
      run: docker compose -f "./devops/local/docker-compose.Local.yaml" down
  unit-tests:
    name: Testes de Unidade
    runs-on: ubuntu-latest
    environment: Production
    needs: build-application
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    - name: Instalação das Dependências do .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Rodar Testes de Unidade na Aplicação
      run: |
        dotnet build
        dotnet test --no-build --verbosity normal ./tsts/unit/Ntickets.UnitTests/Ntickets.UnitTests.csproj
  integration-tests:
    name: Testes de Integração
    runs-on: ubuntu-latest
    environment: Production
    needs: build-application
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    - name: Instalação das Dependências do .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Rodar Testes de Integração na Aplicação
      run: |
        dotnet build
        dotnet test --no-build --verbosity normal ./tsts/integration/Ntickets.IntegrationTests/Ntickets.IntegrationTests.csproj
  sonar:
    name: Análise Estática de Código
    runs-on: ubuntu-latest
    environment: Production
    needs: build-application
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Instalação das Dependências do .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Instalar o Scanner de Análise Estática de Código
      shell: pwsh
      run: |
        New-Item -Path ./.sonar/scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
    - name: Restaurar Dependências da Solução
      run: dotnet restore Ntickets.sln
    - name: Construir Solução e Testar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"OtavioVB_Ntickets" /o:"otaviovb-1" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="app/**,libs/**,tsts/**,**/Migrations/**,**/Controllers/**,**/Mappings/**,**/EntityFrameworkCore/**,**/Dockerfile,**/DependencyInjection.cs,functions/**,**/UseCases/**,**/Program.cs" /d:sonar.exclusions="app/**,libs/**,tsts/**,**/Migrations/**,**/Controllers/**,**/Mappings/**,**/EntityFrameworkCore/**,**/Dockerfile,benchs/**,**/DependencyInjection.cs,functions/**,**/Program.cs"
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./tsts/unit/Ntickets.UnitTests/Ntickets.UnitTests.csproj
        ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  stress-tests:
    name: Testes de Carga/Estresse
    runs-on: ubuntu-latest
    environment: Production
    needs:
      - sonar
      - acceptance-tests
      - integration-tests
      - unit-tests
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3
    - name: Instalação das Dependências do .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Instalação das Dependências do .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restaurar Dependências da Solução
      run: dotnet restore Ntickets.sln
    - name: Implantar Dependências do Docker
      run: docker compose -f "./devops/local/docker-compose.Local.yaml" up -d
    - name: Instalar Ferramenta de Migração do Banco de Dados
      run: |
        dotnet tool install --global dotnet-ef
    - name: Aplicar Migração do Banco de Dados
      run: |
        dotnet ef database update --project "./src/Ntickets.WebApi/Ntickets.WebApi.csproj"
    - name: Executar Aplicação .NET 8
      run: |
        dotnet dev-certs https --trust
        dotnet dev-certs https --check
        dotnet run --project "./src/Ntickets.WebApi/Ntickets.WebApi.csproj" & echo $! > pidfile
    - name: Instalar k6
      run: |
        sudo apt update
        sudo apt install -y k6
    - name: Executar Testes de Carga com k6
      run: |
        k6 run ./tsts/stress/create_tenant_stress_tests.js
    - name: Parar Aplicação
      run: |
        kill $(cat pidfile)
        rm pidfile
    - name: Parar as Dependências do Docker
      if: always() 
      run: docker compose -f "./devops/local/docker-compose.Local.yaml" down